### ISSUE TITLE
Extract logs

### ISSUE THREAD

**Issue by ryscheng** [willscott/grunt-jasmine-chromeapp#10]
When on Shippable, we don't have access to the Chrome context. It'd be helpful to have a debug:true option that allows us to print all logs back out to the terminal

**Comment by willscott** [comment]
Any idea if this is possible?

**Comment by ryscheng** [comment]
Can you overwrite the console object in the context of the generated Chrome
app?

**Comment by agallant** [comment]
Would something like this maybe help? https://www.npmjs.com/package/console-browserify

**Comment by agallant** [comment]
Specifically what I'm envisioning is: https://github.com/soycode/grunt-jasmine-chromeapp/commit/43fc820f5435f7654890a50d2e118f435522dbb8

I'm not sure if there's a good way to test that on shippable without updating the package on npm, so I really don't know if that's the right spot/approach.

**Comment by iislucas** [comment]
If it outputs to STDOUT, I think we're good and should try cutting a release. :) Thanks!

**Comment by ryscheng** [comment]
I think we're talking about something different @soycode. Your commit only tries to add a console object in the task if it is missing. 

This issue is more about extracting logs from the context of the spec. For example, if some code in the test logs something e.g. 
describe("test", function() {
  it("logs something", function() {
    console.log("log");
  })
});

This happens in the context of the chrome packaged app that is generated. The logs are stuck in the background page of the chrome packaged app and we need some way to retrieve them and report them back out to the command line. 

Another way to look at it is, when we currently debug tests with jasmine_chromeapp, we have to set keepRunner:true and then pull up a developer console on the running app to see what went wrong. Imagine a case when we can't set keepRunner:true and we have to debug purely from a single run. Then we'd like to extract those logs out.

**Comment by agallant** [comment]
Yeah just chatted w/Will and essentially the problem is as you said, that the logs are going to the "wrong" place rather than not going anywhere. Any fix is likely not as trivial as what I'd hoped in that commit, and interactive debugging with the actual docker image is probably best - so maybe figuring out some scripting/tooling to facilitate that would have better bang for buck.

**Comment by willscott** [comment]
Two thoughts:
Having console errors is nice, but generally still not enough by themselves to debug.

We should be able to have the instance of chrome that's run by shippable expose a remote debugging port. We've got a stable, repeatable docker image there, which can be replicated on our machines. Allowing external environment to dictate that the grunt task should `keepRunner` and expose a remote debug port would give us interactive debugging on that repeatable configuration.

**Comment by iislucas** [comment]
I'll put some time on cal to discuss. I think logs would help us a good deal; if we could actually ssh in, that would be amazing, but I expect that might be a lot more work.

**Comment by willscott** [comment]
Added in 6507cec6b3758e645f4d94bb452afc107952d7bd. new version forthcoming.

**Comment by iislucas** [comment]
woohooo! Thank you!

**Comment by trevj** [comment]
Wow! Awesome!
